postgresql:
  enabled: true
  auth:
    username: tamuser
    password: tampassword
    database: deploymanager

config:
  replicaCount: 1
  appPort: 8000
  type: LoadBalancer
  nodePort: 30311
  debug: "True"
  logLevel: DEBUG
  guiHost: portal
  guiPort: 8000
  cmaHost: configmanager
  cmaPort: 8000
  smaHost: suitemanager
  smaPort: 8000
  tmaHost: testmanager
  tmaPort: 8000
  rmaHost: resultsmanager
  rmaPort: 8000
  apgHost: apigateway
  apgPort: 8000
  dmaHost: deploymanager
  dmaPort: 8000

image:
  repository: ghcr.io/cdecatapult/soniclabs-deploymanager
  pullPolicy: Always
  tag: sha256:853dc8715d72807ab91a763a78feef6eff29d2b2200dba56c5d2bbf2c5457cd9
  pullSecrets: ['soniclabs']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
