postgresql:
  enabled: true
  auth:
    username: tamuser
    password: tampassword
    database: suitemanager

config:
  replicaCount: 1
  appPort: 8000
  type: LoadBalancer
  nodePort: 30313
  debug: "True"
  logLevel: DEBUG
  guiHost: portal
  guiPort: 8000
  cmaHost: configmanager
  cmaPort: 8000
  smaHost: suitemanager
  smaPort: 8000
  tmaHost: testmanager
  tmaPort: 8000
  rmaHost: resultsmanager
  rmaPort: 8000
  apgHost: apigateway
  apgPort: 8000
  dmaHost: deploymanager
  dmaPort: 8000

image:
  repository: ghcr.io/cdecatapult/soniclabs-suitemanager
  pullPolicy: Always
  tag: sha256:b28bbaae9d67c977d2155ed9fe7503e5561d8380ca55ef6980b6735140be6897
  pullSecrets: ['soniclabs']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
