postgresql:
  enabled: true
  auth:
    username: tamuser
    password: tampassword
    database: testmanager

config:
  replicaCount: 1
  appPort: 8000
  type: LoadBalancer
  nodePort: 30324
  debug: "True"
  logLevel: DEBUG
  guiHost: portal
  guiPort: 8000
  cmaHost: configmanager
  cmaPort: 8000
  camHost: casemanager
  camPort: 8000
  tmaHost: testmanager
  tmaPort: 8000
  rmaHost: resultsmanager
  rmaPort: 8000
  apgHost: apigateway
  apgPort: 8000
  dmaHost: deploymanager
  dmaPort: 8000

image:
  repository: ghcr.io/cdecatapult/soniclabs-testmanager
  pullPolicy: Always
  tag: sha256:244f8164e526e99a1c9e634679b24fbbd38577e528eb219e0362514bac951324
  pullSecrets: ['soniclabs']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
