apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testmanager.fullname" . }}-secret
  labels:
    {{- include "testmanager.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  CONTROL_USERNAME: {{ .Values.config.controlUsername | b64enc | quote }}
  CONTROL_PASSWORD: {{ .Values.config.controlPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testmanager.fullname" . }}-ssh-key
  labels:
    {{- include "testmanager.labels" . | nindent 4 }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.config.sshKey | b64enc | quote }}
