apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resultsmanager.fullname" . }}-pcap-storage
  labels:
    {{- include "resultsmanager.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.config.pcapStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.config.pcapStorage.size | quote }}
  storageClassName: {{ .Values.config.pcapStorage.storageClassName | quote }}
