postgresql:
  enabled: true
  auth:
    username: tamuser
    password: tampassword
    database: resultsmanager

config:
  replicaCount: 1
  appPort: 8000
  type: LoadBalancer
#   nodePort: 30332
  debug: "True"
  logLevel: DEBUG
  guiHost: portal
  guiPort: 8000
  cmaHost: configmanager
  cmaPort: 8000
  smaHost: suitemanager
  smaPort: 8000
  tmaHost: testmanager
  tmaPort: 8000
  rmaHost: resultsmanager
  rmaPort: 8000
  apgHost: apigateway
  apgPort: 8000
  dmaHost: deploymanager
  dmaPort: 8000

image:
  repository: ghcr.io/cdecatapult/soniclabs-resultsmanager
  pullPolicy: Always
  tag: sha256:8b7229f2a63624b259f3982e926a5ba2dc2741532e41e094131b06f1e9f2280d
  pullSecrets: ['soniclabs']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
