## @section Portal Parameters
##
config:
## @param config.replicaCount The amount of containers to run
  replicaCount: 1
## @param config.type The type of service to create
  type: LoadBalancer
  ## @param config.appPort The port to expose the service and application on
  appPort: 80
  ## @param config.nodePort The nodePort to use if the the service type is LoadBalancer or NodePort
  nodePort: 30342
  ## @param config.commonAnnotations The annotations to set on the Portal application
  commonAnnotations: {}
  cma:
    ## @param config.cma.host The hostname of the Config Manager service
    host: configmanager
    ## @param config.cma.port The port of the Config Manager service
    port: 8000
  sma:
    ## @param config.sma.host The hostname of the Suite Manager service
    host: suitemanager
    ## @param config.sma.port The port of the Suite Manager service
    port: 8000
  tma:
    ## @param config.tma.host The hostname of the Test Manager service
    host: testmanager
    ## @param config.tma.port The port of the Test Manager service
    port: 8000
  rma:
    ## @param config.rma.host The hostname of the Results Manager service
    host: resultsmanager
    ## @param config.rma.port The port of the Results Manager service
    port: 8000
  dma:
    ## @param config.dma.host The hostname of the Deploy Manager service
    host: deploymanager
    ## @param config.dma.port The port of the Deploy Manager service
    port: 8000

## @section ConfigManager Image Parameters
image:
  ## @param image.repository The repository to use for the Portal image
  repository: ghcr.io/cdecatapult/soniclabs-portal
  ## @param image.pullPolicy The pull policy to use for the Portal image
  pullPolicy: Always
  ## @param image.tag The tag to use for the Portal image
  tag: v0.0.1
  ## @param image.pullSecrets The pull secrets to use for the Portal image
  pullSecrets: ['soniclabs']

## @section Portal Ingress parameters
##
ingress:
  ## @param ingress.enabled Whether or not to enable the ingress for the Portal application
  enabled: true
  ## @param ingress.annotations The annotations to set on the ingress for the Portal application
  annotations: {}
  ## @param ingress.ingressClassName The ingress class to use for the Portal application
  ingressClassName: ""
  ## @param ingress.hostname The hostname to use for the Portal application
  hostname: portal.local
  ## @extra ingress.paths The paths to use for the Portal application
  paths:
  ## @param ingress.paths[0].path The path to use for the Portal application
  ## @param ingress.paths[0].pathType The path type to use for the Portal application
    - path: /
      pathType: Prefix

## @section Portal ServiceAccount parameters
serviceAccount:
  ## @param serviceAccount.create Whether or not to create a service account for the Portal service
  create: false
  ## @param serviceAccount.annotations The annotations to use for the Portal service account
  annotations: {}
  ## @param serviceAccount.name The name of the service account to use for the Portal service
  name: ""
